### ISSUE TITLE
dynamic translations

### ISSUE THREAD

**Issue by gedw99** [muonsoft/validation#62]
hey @strider2038

I noticed the translation files are static, and not dynamic.

Here is an example of dynamic. Its uses the standard golang approach for language translation. 
https://github.com/PhraseApp-Blog/go-internationalization/blob/master/examples/dynamic/locales/el/messages.gotext.json

I am wondering if this is something you need ?

**Comment by strider2038** [comment]
Hello, @gedw99 

What do you mean by translations files are static? JSON file is a static file too. Do you want a feature for loading translations from files? Or an ability to hot-reload translations from an external source such as files or relational databases?

**Comment by gedw99** [comment]
hey @strider2038 

yes you got it. I am needing to load translations from a file or DB.  

The use case is to allow a DB to be used by all developers for many apps.  This allows all machine translations and then human overrides to be done by a 2nd system using that DB.

**Comment by strider2038** [comment]
@gedw99 I'm suggesting using an interface `Translator`.

```golang
type Translator interface {
	Translate(tag language.Tag, message string, pluralCount int) string
}
```

You can do your implementation of a translator that loads any of your translations dynamically from the sources you want. To inject custom translator into the validator use `SetTranslator()` option. See full code changes in the pull request https://github.com/muonsoft/validation/pull/64

What do you think?
